use_frameworks!

target 'KenticoKontentDelivery_Example' do
  pod 'KenticoKontentDelivery', :path => '../'

  target 'KenticoKontentDelivery_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
